apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- db-helmrelease.yaml
- db-helmrepository.yaml
- github-instavote.yaml
- instavote-gitrepository.yaml
- instavote-webhook.yaml
- redis-staging-alert.yaml
- redis-staging-kustomization.yaml
- result-helmrelease.yaml
- result-imagepolicy.yaml
- result-imagerepository.yaml
- result-imageupdateautomation.yaml
- secrets/dockerhub-creds.yaml
- secrets/github-instavote-deploy.yaml
- secrets/github-token.yaml
- secrets/slack-url.yaml
- secrets/webhook-token.yaml
- slack-alert-provider.yaml
- slack-notif-alert.yaml
- vote-imagepolicy.yaml
- vote-imagerepository.yaml
- vote-imageupdateautomation.yaml
- vote-staging-alert.yaml
- vote-staging-kustomization.yaml
- worker-staging-alert.yaml
- worker-staging-kustomization.yaml
