apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: instavote-secrets
  namespace: instavote
spec:
  interval: 2m
  path: ./secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: instavote-deploy
  decryption:
    provider: sops
    secretRef:
      name: sops-age
