---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tekton-ci
  namespace: instavote
spec:
  interval: 1m
  path: ./tekton-ci/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: instavote-deploy
  targetNamespace: instavote
  timeout: 2m0s
