---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: worker-staging
  namespace: instavote
spec:
  healthChecks:
  - kind: Deployment
    name: worker
    namespace: instavote
  interval: 1m
  path: ./kustomize/worker/staging/
  prune: true
  sourceRef:
    kind: GitRepository
    name: instavote-deploy
  targetNamespace: instavote
  timeout: 2m0s
