apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- eventlistener.yaml
- instavote-ci-pipeline.yaml
- triggerbinding-result.yaml
- triggerbinding-vote.yaml
- triggertemplate-result.yaml
- triggertemplate-vote.yaml
